# Generated by Django 4.1.1 on 2022-09-08 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueOfLegends', '0003_alter_friend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
