# Generated by Django 4.1.1 on 2022-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueOfLegends', '0004_alter_friend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lolusername',
            field=models.CharField(default='', max_length=255),
        ),
    ]
