# Generated by Django 4.1.1 on 2022-09-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueOfLegends', '0005_user_lolusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
