# Generated by Django 4.1.1 on 2022-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueOfLegends', '0008_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lolusername',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
