# Generated by Django 4.1.1 on 2022-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueOfLegends', '0009_alter_user_lolusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lolusername',
            field=models.CharField(default='', max_length=255),
        ),
    ]
